application: Suprosity Landing page
version: 1
runtime: python
api_version: 1
threadsafe: yes

default_expiration: "30d"

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static